name: Bundle Impact

on:
  pull_request_target:
    branches: [main, next]
    types: [opened, synchronize]

jobs:
  bundle-impact:
    name: Calculate Bundle Impact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: pnpm

      - run: |
          pnpm install -C scripts/bundle-impact

      - name: Run Bundle Impact
        env:
          RADASHI_BOT_TOKEN: ${{ secrets.RADASHI_BOT_TOKEN }}
          TARGET_BRANCH: ${{ github.base_ref }}
        run: |
          scripts/bundle-impact/node_modules/.bin/tsx pr-bundle-impact.ts ${{ github.event.number }}
