name: Publish to JSR

on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: '22.x'
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install -C scripts/versions
          pnpm install -C scripts/radashi-db

      - name: Publish to JSR
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          ./scripts/versions/node_modules/.bin/tsx ./scripts/versions/ci-publish-jsr.ts
