name: Publish Preview Release

on:
  issue_comment:
    types: [created]

jobs:
  publish-preview:
    if: ${{ github.event.issue.pull_request && github.event.comment.user.id == github.event.issue.user.id && startsWith(github.event.comment.body, '/publish') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: pnpm
      - name: Get package version
        id: package-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      - name: Get commit SHA
        id: commit-sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      - name: Update package version
        run: npm version ${{ steps.package-version.outputs.version }}-pr${{ github.event.issue.number }}.${{ steps.commit-sha.outputs.sha }} --no-git-tag-version
      - name: Publish to NPM
        run: npm publish --tag pr${{ github.event.issue.number }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: React to issue comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          reactions: rocket
          token: ${{ secrets.GITHUB_TOKEN }}
