name: Register PR In Database

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize, closed]

jobs:
  register-pr:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm install -C scripts/functions
          pnpm install -C scripts/radashi-db

      - name: Register PR
        uses: actions/github-script@v6
        env:
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          NODE_OPTIONS: '--import scripts/functions/node_modules/tsx/dist/esm/index.mjs'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = await import('${{ github.workspace }}/scripts/functions/ci-register-pr.ts')
            await script.run(context.payload.pull_request, github)
