name: Register PR In Database

on:
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize, closed]

jobs:
  register-pr:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm install -C scripts/functions
          pnpm install -C scripts/radashi-db

      - name: Register PR
        uses: actions/github-script@v6
        env:
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const root = '${{ github.workspace }}/scripts/functions'
            const { tsImport } = await import(root + '/node_modules/tsx/dist/esm/api/index.cjs')
            const script = await tsImport('./ci-register-pr.ts', root)
            await script.run(context.payload.pull_request, github)
