name: 'Release'
on:
  push:
    branches: [master]
jobs:
  check:
    name: 'Check if release is needed'
    runs-on: 'ubuntu-latest'
    outputs:
      exists: ${{ steps.check-tag.outputs.exists }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Version
        id: get-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - uses: mukunku/tag-exists-action@v1.0.0
        id: check-tag
        with:
          tag: v${{ steps.get-version.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    name: 'Release'
    needs: check
    if: needs.check.outputs.exists == 'false'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Get Current Version
        id: get-version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Make Artifacts
        run: yarn archive:zip && yarn archive:gzip
      - name: Create Release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get-version.outputs.version}}
          tag_name: v${{ steps.get-version.outputs.version}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Artifact (zip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./archive.zip
          asset_name: radash-${{ steps.get-version.outputs.version}}-source.zip
          asset_content_type: application/zip
      - name: Upload Release Artifact (gzip)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./archive.tar.gz
          asset_name: radash-${{ steps.get-version.outputs.version}}-source.tar.gz
          asset_content_type: application/gzip
